### PR TITLE
Setup test project

### PR DESCRIPTION
**Pull request by viktor-podzigun**
Hi, thank you for looking at it.

I've put some comments on needed changes for each environment in `build.sbt`.

Thanks again and looking forward to your feedback.

### CODE REVIEW

**Comment by gslowikowski** [comment]
Thank you @viktor-podzigun 

I have some questions:

1. Why `sbt-scalajs-bundler` is required for `JSDOMNodeJSEnv`? Can't we create a project with this env, but without the bundler plugin?

2. Does it make sense to fix scoverage plugin if for now we are not able to verify if it's working afterwards (because bundler needs patching)?

3. I tried to create a project with `PhantomJSEnv`, but had strange `java.lang.NoClassDefFoundError: org/eclipse/jetty/util/log/Logger` error. Can you test this env as well?

At the end I'd like to test all ScalaJs environments.

P.S.
I don't know ScalaJs, learning it now, so please, be patient when I will ask dummy questions :)

**Comment by viktor-podzigun** [comment]
Hi @gslowikowski,

1. You are correct, `sbt-scalajs-bundler` is not required, it's just one more use case/env, since it contains custom `JSDOMNodeJSEnv` and many people using it we should support it as well (see discussion [here](https://github.com/scalacenter/scalajs-bundler/issues/197)).
I've also created corresponding PR with required changes for standalone `JSDOMNodeJSEnv `:
https://github.com/scala-js/scala-js-env-jsdom-nodejs/pull/19

2. If we agree on the approach, and the changes are compatible (no regression for current behaviour), I think, we are safe to apply the fix.

3. It should not affect `PhantomJSEnv `, but I don't have experience with how to set it up correctly, maybe @sjrd could advise here?

You are doing great with `scala.js`, don't hesitate to ask, if you need any help!

**Comment by sjrd** [comment]
About `PhantomJSEnv`, don't bother: it's dying. PhantomJS itself is basically dead; its development has been officially suspended.

**Comment by viktor-podzigun** [comment]
Closing in favor of https://github.com/scoverage/scalac-scoverage-plugin/pull/456

**Pull request closed without merging**
